id: IC4C543CC
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:14.354216
last_modified: 2023-01-04 11:28:14.354234
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  ED44:
    title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
    base_file: ED44.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
